Sprint 1
lolliuym/middle.messenger.praktikum.yandex pull request #1
Opened 2022-07-31 09:50 UTC by lolliuym

2022-07-31 10:57 UTC, ivan-infro requested changes

2022-07-31 10:57 UTC, ivan-infro commented on .gitignore
> +dist
Необходимо добавить .parcel-cache в .gitignore и удалить файлы кеша из репозитория

2022-07-31 10:57 UTC, ivan-infro commented on README.md
> -# sprint_1
Ветка main сейчас не должна содержать коммиты первого спринта

2022-07-31 10:57 UTC, ivan-infro commented on src/assets/styles/buttons.scss
> + .btn {
Дублирует файл components/button/style.scss, необходимо оставить только один

2022-07-31 10:57 UTC, ivan-infro commented on src/index.js
> +console.log(tpl);
Не оставляйте в коде console.log, это затрудняет чтение кода и засоряет вывод консоли

2022-07-31 10:57 UTC, ivan-infro commented on src/index.js
> +window.createButton = (id, value) => {
Все страницы должны быть разбиты на утилиты и модули, глобальные переменные использоваться не должны

2022-08-16 17:42 UTC, merged

2022-08-24 18:41 UTC, lolliuym commented on .gitignore
> +dist
добавил это в .gitignore

2022-08-24 18:43 UTC, lolliuym commented on src/assets/styles/buttons.scss
> + .btn {
Исправил

2022-08-24 18:44 UTC, lolliuym commented on README.md
> -# sprint_1
попробую удалить все коммиты, относящиеся к спринту 1

2022-08-24 18:45 UTC, lolliuym commented on README.md
> -# sprint_1
попробую удалить все коммиты, относящиеся к спринту 1